name: TwosideKeeper4
main: sig.plugin.TwosideKeeper.TwosideKeeper4.main
version: 3.99a
loadbefore: [aPlugin]
commands:
   scan:
      description: Analyzes the item found above the block you are looking at.
      usage: /scan
      permission: TwosideKeeper.admin
      permission-message: You don't have permission to scan a block.
   pedestal_check:
      description: Checks if the block is a pedestal.
      usage: /pedestal_check
      permission: TwosideKeeper.admin
      permission-message: You don't have permission to check this pedestal.
   pedestal_create:
      description: Creates a pedestal.
      usage: /pedestal_create
      permission: TwosideKeeper.admin
      permission-message: You don't have permission to create a pedestal.